package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"strconv"

	"github.com/example/graphql-mysql-api/pkg/api/graph/generated"
	"github.com/example/graphql-mysql-api/pkg/models"
)

// ID is the resolver for the id field.
func (r *accountResolver) ID(ctx context.Context, obj *models.Account) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *accountResolver) UserID(ctx context.Context, obj *models.Account) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// CurrencyID is the resolver for the currencyId field.
func (r *accountResolver) CurrencyID(ctx context.Context, obj *models.Account) (string, error) {
	panic(fmt.Errorf("not implemented: CurrencyID - currencyId"))
}

// ID is the resolver for the id field.
func (r *categoryResolver) ID(ctx context.Context, obj *models.Category) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *categoryResolver) UserID(ctx context.Context, obj *models.Category) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// ID is the resolver for the id field.
func (r *currencyResolver) ID(ctx context.Context, obj *models.Currency) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ID is the resolver for the id field.
func (r *exchangeResolver) ID(ctx context.Context, obj *models.Exchange) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *exchangeResolver) UserID(ctx context.Context, obj *models.Exchange) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// FromAccountID is the resolver for the fromAccountId field.
func (r *exchangeResolver) FromAccountID(ctx context.Context, obj *models.Exchange) (string, error) {
	panic(fmt.Errorf("not implemented: FromAccountID - fromAccountId"))
}

// ToAccountID is the resolver for the toAccountId field.
func (r *exchangeResolver) ToAccountID(ctx context.Context, obj *models.Exchange) (string, error) {
	panic(fmt.Errorf("not implemented: ToAccountID - toAccountId"))
}

// FromCurrencyID is the resolver for the fromCurrencyId field.
func (r *exchangeResolver) FromCurrencyID(ctx context.Context, obj *models.Exchange) (string, error) {
	panic(fmt.Errorf("not implemented: FromCurrencyID - fromCurrencyId"))
}

// ToCurrencyID is the resolver for the toCurrencyId field.
func (r *exchangeResolver) ToCurrencyID(ctx context.Context, obj *models.Exchange) (string, error) {
	panic(fmt.Errorf("not implemented: ToCurrencyID - toCurrencyId"))
}

// FeeCurrencyID is the resolver for the feeCurrencyId field.
func (r *exchangeResolver) FeeCurrencyID(ctx context.Context, obj *models.Exchange) (*string, error) {
	panic(fmt.Errorf("not implemented: FeeCurrencyID - feeCurrencyId"))
}

// ID is the resolver for the id field.
func (r *expenseResolver) ID(ctx context.Context, obj *models.Expense) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *expenseResolver) UserID(ctx context.Context, obj *models.Expense) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// AccountID is the resolver for the accountId field.
func (r *expenseResolver) AccountID(ctx context.Context, obj *models.Expense) (string, error) {
	panic(fmt.Errorf("not implemented: AccountID - accountId"))
}

// CategoryID is the resolver for the categoryId field.
func (r *expenseResolver) CategoryID(ctx context.Context, obj *models.Expense) (*string, error) {
	panic(fmt.Errorf("not implemented: CategoryID - categoryId"))
}

// CurrencyID is the resolver for the currencyId field.
func (r *expenseResolver) CurrencyID(ctx context.Context, obj *models.Expense) (string, error) {
	panic(fmt.Errorf("not implemented: CurrencyID - currencyId"))
}

// ID is the resolver for the id field.
func (r *incomeResolver) ID(ctx context.Context, obj *models.Income) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *incomeResolver) UserID(ctx context.Context, obj *models.Income) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// AccountID is the resolver for the accountId field.
func (r *incomeResolver) AccountID(ctx context.Context, obj *models.Income) (string, error) {
	panic(fmt.Errorf("not implemented: AccountID - accountId"))
}

// CategoryID is the resolver for the categoryId field.
func (r *incomeResolver) CategoryID(ctx context.Context, obj *models.Income) (*string, error) {
	panic(fmt.Errorf("not implemented: CategoryID - categoryId"))
}

// CurrencyID is the resolver for the currencyId field.
func (r *incomeResolver) CurrencyID(ctx context.Context, obj *models.Income) (string, error) {
	panic(fmt.Errorf("not implemented: CurrencyID - currencyId"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input generated.NewUserInput) (*models.User, error) {
	user := &models.User{
		Email: input.Email,
		Name:  input.Name,
	}

	if err := r.DB.Create(user).Error; err != nil {
		return nil, err
	}

	return user, nil
}

// CreateCurrency is the resolver for the createCurrency field.
func (r *mutationResolver) CreateCurrency(ctx context.Context, input generated.NewCurrencyInput) (*models.Currency, error) {
	panic(fmt.Errorf("not implemented: CreateCurrency - createCurrency"))
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input generated.NewAccountInput) (*models.Account, error) {
	panic(fmt.Errorf("not implemented: CreateAccount - createAccount"))
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input generated.NewCategoryInput) (*models.Category, error) {
	panic(fmt.Errorf("not implemented: CreateCategory - createCategory"))
}

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input generated.NewExpenseInput) (*models.Expense, error) {
	panic(fmt.Errorf("not implemented: CreateExpense - createExpense"))
}

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input generated.NewIncomeInput) (*models.Income, error) {
	panic(fmt.Errorf("not implemented: CreateIncome - createIncome"))
}

// CreateExchange is the resolver for the createExchange field.
func (r *mutationResolver) CreateExchange(ctx context.Context, input generated.NewExchangeInput) (*models.Exchange, error) {
	panic(fmt.Errorf("not implemented: CreateExchange - createExchange"))
}

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input generated.NewTransferInput) (*models.Transfer, error) {
	panic(fmt.Errorf("not implemented: CreateTransfer - createTransfer"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	var users []*models.User
	if err := r.DB.Find(&users).Error; err != nil {
		return nil, err
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	var user models.User
	if err := r.DB.First(&user, id).Error; err != nil {
		return nil, err
	}
	return &user, nil
}

// Currencies is the resolver for the currencies field.
func (r *queryResolver) Currencies(ctx context.Context) ([]*models.Currency, error) {
	panic(fmt.Errorf("not implemented: Currencies - currencies"))
}

// Currency is the resolver for the currency field.
func (r *queryResolver) Currency(ctx context.Context, id string) (*models.Currency, error) {
	panic(fmt.Errorf("not implemented: Currency - currency"))
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*models.Account, error) {
	panic(fmt.Errorf("not implemented: Accounts - accounts"))
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*models.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// UserAccounts is the resolver for the userAccounts field.
func (r *queryResolver) UserAccounts(ctx context.Context, userID string) ([]*models.Account, error) {
	panic(fmt.Errorf("not implemented: UserAccounts - userAccounts"))
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*models.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*models.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// UserCategories is the resolver for the userCategories field.
func (r *queryResolver) UserCategories(ctx context.Context, userID string) ([]*models.Category, error) {
	panic(fmt.Errorf("not implemented: UserCategories - userCategories"))
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context) ([]*models.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id string) (*models.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// UserTransactions is the resolver for the userTransactions field.
func (r *queryResolver) UserTransactions(ctx context.Context, userID string) ([]*models.Transaction, error) {
	panic(fmt.Errorf("not implemented: UserTransactions - userTransactions"))
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context) ([]*models.Expense, error) {
	panic(fmt.Errorf("not implemented: Expenses - expenses"))
}

// Expense is the resolver for the expense field.
func (r *queryResolver) Expense(ctx context.Context, id string) (*models.Expense, error) {
	panic(fmt.Errorf("not implemented: Expense - expense"))
}

// UserExpenses is the resolver for the userExpenses field.
func (r *queryResolver) UserExpenses(ctx context.Context, userID string) ([]*models.Expense, error) {
	panic(fmt.Errorf("not implemented: UserExpenses - userExpenses"))
}

// Incomes is the resolver for the incomes field.
func (r *queryResolver) Incomes(ctx context.Context) ([]*models.Income, error) {
	panic(fmt.Errorf("not implemented: Incomes - incomes"))
}

// Income is the resolver for the income field.
func (r *queryResolver) Income(ctx context.Context, id string) (*models.Income, error) {
	panic(fmt.Errorf("not implemented: Income - income"))
}

// UserIncomes is the resolver for the userIncomes field.
func (r *queryResolver) UserIncomes(ctx context.Context, userID string) ([]*models.Income, error) {
	panic(fmt.Errorf("not implemented: UserIncomes - userIncomes"))
}

// Exchanges is the resolver for the exchanges field.
func (r *queryResolver) Exchanges(ctx context.Context) ([]*models.Exchange, error) {
	panic(fmt.Errorf("not implemented: Exchanges - exchanges"))
}

// Exchange is the resolver for the exchange field.
func (r *queryResolver) Exchange(ctx context.Context, id string) (*models.Exchange, error) {
	panic(fmt.Errorf("not implemented: Exchange - exchange"))
}

// UserExchanges is the resolver for the userExchanges field.
func (r *queryResolver) UserExchanges(ctx context.Context, userID string) ([]*models.Exchange, error) {
	panic(fmt.Errorf("not implemented: UserExchanges - userExchanges"))
}

// Transfers is the resolver for the transfers field.
func (r *queryResolver) Transfers(ctx context.Context) ([]*models.Transfer, error) {
	panic(fmt.Errorf("not implemented: Transfers - transfers"))
}

// Transfer is the resolver for the transfer field.
func (r *queryResolver) Transfer(ctx context.Context, id string) (*models.Transfer, error) {
	panic(fmt.Errorf("not implemented: Transfer - transfer"))
}

// UserTransfers is the resolver for the userTransfers field.
func (r *queryResolver) UserTransfers(ctx context.Context, userID string) ([]*models.Transfer, error) {
	panic(fmt.Errorf("not implemented: UserTransfers - userTransfers"))
}

// ID is the resolver for the id field.
func (r *transactionResolver) ID(ctx context.Context, obj *models.Transaction) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *transactionResolver) UserID(ctx context.Context, obj *models.Transaction) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// AccountID is the resolver for the accountId field.
func (r *transactionResolver) AccountID(ctx context.Context, obj *models.Transaction) (string, error) {
	panic(fmt.Errorf("not implemented: AccountID - accountId"))
}

// CategoryID is the resolver for the categoryId field.
func (r *transactionResolver) CategoryID(ctx context.Context, obj *models.Transaction) (*string, error) {
	panic(fmt.Errorf("not implemented: CategoryID - categoryId"))
}

// CurrencyID is the resolver for the currencyId field.
func (r *transactionResolver) CurrencyID(ctx context.Context, obj *models.Transaction) (string, error) {
	panic(fmt.Errorf("not implemented: CurrencyID - currencyId"))
}

// ID is the resolver for the id field.
func (r *transferResolver) ID(ctx context.Context, obj *models.Transfer) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *transferResolver) UserID(ctx context.Context, obj *models.Transfer) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// FromAccountID is the resolver for the fromAccountId field.
func (r *transferResolver) FromAccountID(ctx context.Context, obj *models.Transfer) (string, error) {
	panic(fmt.Errorf("not implemented: FromAccountID - fromAccountId"))
}

// ToAccountID is the resolver for the toAccountId field.
func (r *transferResolver) ToAccountID(ctx context.Context, obj *models.Transfer) (string, error) {
	panic(fmt.Errorf("not implemented: ToAccountID - toAccountId"))
}

// CurrencyID is the resolver for the currencyId field.
func (r *transferResolver) CurrencyID(ctx context.Context, obj *models.Transfer) (string, error) {
	panic(fmt.Errorf("not implemented: CurrencyID - currencyId"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// Accounts is the resolver for the accounts field.
func (r *userResolver) Accounts(ctx context.Context, obj *models.User) ([]*models.Account, error) {
	panic(fmt.Errorf("not implemented: Accounts - accounts"))
}

// Categories is the resolver for the categories field.
func (r *userResolver) Categories(ctx context.Context, obj *models.User) ([]*models.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *models.User) ([]*models.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}

// Expenses is the resolver for the expenses field.
func (r *userResolver) Expenses(ctx context.Context, obj *models.User) ([]*models.Expense, error) {
	panic(fmt.Errorf("not implemented: Expenses - expenses"))
}

// Incomes is the resolver for the incomes field.
func (r *userResolver) Incomes(ctx context.Context, obj *models.User) ([]*models.Income, error) {
	panic(fmt.Errorf("not implemented: Incomes - incomes"))
}

// Exchanges is the resolver for the exchanges field.
func (r *userResolver) Exchanges(ctx context.Context, obj *models.User) ([]*models.Exchange, error) {
	panic(fmt.Errorf("not implemented: Exchanges - exchanges"))
}

// Transfers is the resolver for the transfers field.
func (r *userResolver) Transfers(ctx context.Context, obj *models.User) ([]*models.Transfer, error) {
	panic(fmt.Errorf("not implemented: Transfers - transfers"))
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Currency returns CurrencyResolver implementation.
func (r *Resolver) Currency() CurrencyResolver { return &currencyResolver{r} }

// Exchange returns ExchangeResolver implementation.
func (r *Resolver) Exchange() ExchangeResolver { return &exchangeResolver{r} }

// Expense returns ExpenseResolver implementation.
func (r *Resolver) Expense() ExpenseResolver { return &expenseResolver{r} }

// Income returns IncomeResolver implementation.
func (r *Resolver) Income() IncomeResolver { return &incomeResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

// Transfer returns TransferResolver implementation.
func (r *Resolver) Transfer() TransferResolver { return &transferResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// Type aliases for generated resolver interfaces
type (
	AccountResolver   = generated.AccountResolver
	CategoryResolver  = generated.CategoryResolver
	CurrencyResolver  = generated.CurrencyResolver
	ExchangeResolver  = generated.ExchangeResolver
	ExpenseResolver   = generated.ExpenseResolver
	IncomeResolver    = generated.IncomeResolver
	MutationResolver  = generated.MutationResolver
	QueryResolver     = generated.QueryResolver
	TransactionResolver = generated.TransactionResolver
	TransferResolver  = generated.TransferResolver
	UserResolver      = generated.UserResolver
)

type accountResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type currencyResolver struct{ *Resolver }
type exchangeResolver struct{ *Resolver }
type expenseResolver struct{ *Resolver }
type incomeResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
type transferResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
