package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"strconv"

	"github.com/example/graphql-mysql-api/pkg/api/graph/generated"
	"github.com/example/graphql-mysql-api/pkg/middleware"
	"github.com/example/graphql-mysql-api/pkg/models"
	"github.com/example/graphql-mysql-api/pkg/utils"
)


// FeeCurrencyID is the resolver for the feeCurrencyId field.
func (r *exchangeResolver) FeeCurrencyID(ctx context.Context, obj *models.Exchange) (*string, error) {
	if obj.FeeCurrencyID == nil {
		return nil, nil
	}
	id := strconv.FormatUint(uint64(*obj.FeeCurrencyID), 10)
	return &id, nil
}

// CategoryID is the resolver for the categoryId field.
func (r *expenseResolver) CategoryID(ctx context.Context, obj *models.Expense) (*string, error) {
	if obj.CategoryID == nil {
		return nil, nil
	}
	id := strconv.FormatUint(uint64(*obj.CategoryID), 10)
	return &id, nil
}

// CategoryID is the resolver for the categoryId field.
func (r *incomeResolver) CategoryID(ctx context.Context, obj *models.Income) (*string, error) {
	if obj.CategoryID == nil {
		return nil, nil
	}
	id := strconv.FormatUint(uint64(*obj.CategoryID), 10)
	return &id, nil
}

// CurrencyID is the resolver for the currencyId field.
func (r *incomeResolver) CurrencyID(ctx context.Context, obj *models.Income) (string, error) {
	return strconv.FormatUint(uint64(obj.CurrencyID), 10), nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input generated.NewUserInput) (*generated.AuthPayload, error) {
	// Check if user already exists
	var existingUser models.User
	if err := r.DB.Where("email = ?", input.Email).First(&existingUser).Error; err == nil {
		return nil, fmt.Errorf("user with email %s already exists", input.Email)
	}

	// Hash password
	hashedPassword, err := utils.HashPassword(input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}

	// Create user
	user := &models.User{
		Email:    input.Email,
		Name:     input.Name,
		Password: hashedPassword,
	}

	if err := r.DB.Create(user).Error; err != nil {
		return nil, fmt.Errorf("failed to create user: %v", err)
	}

	// Generate token
	token, err := utils.GenerateToken(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %v", err)
	}

	return &generated.AuthPayload{
		Token: token,
		User:  user,
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input generated.LoginInput) (*generated.AuthPayload, error) {
	// Find user by email
	var user models.User
	if err := r.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		return nil, fmt.Errorf("invalid email or password")
	}

	// Check password
	if !utils.CheckPasswordHash(input.Password, user.Password) {
		return nil, fmt.Errorf("invalid email or password")
	}

	// Generate token
	token, err := utils.GenerateToken(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %v", err)
	}

	return &generated.AuthPayload{
		Token: token,
		User:  &user,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// In a stateless JWT system, logout is typically handled client-side
	// by removing the token. However, we can validate the user is authenticated.
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Token invalidation would require a token blacklist (Redis, database, etc.)
	// For now, we just return success if user is authenticated
	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input generated.NewUserInput) (*models.User, error) {
	user := &models.User{
		Email: input.Email,
		Name:  input.Name,
	}

	if err := r.DB.Create(user).Error; err != nil {
		return nil, err
	}

	return user, nil
}

// CreateCurrency is the resolver for the createCurrency field.
func (r *mutationResolver) CreateCurrency(ctx context.Context, input generated.NewCurrencyInput) (*models.Currency, error) {
	return nil, fmt.Errorf("not implemented: CreateCurrency - createCurrency")
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input generated.NewCategoryInput) (*models.Category, error) {
	userID, err := strconv.ParseUint(input.UserID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %v", err)
	}

	category := &models.Category{
		UserID:   uint(userID),
		Name:     input.Name,
		Type:     input.Type,
		IsActive: true,
	}

	if input.Color != nil {
		category.Color = input.Color
	}
	if input.Icon != nil {
		category.Icon = input.Icon
	}

	if err := r.DB.Create(category).Error; err != nil {
		return nil, fmt.Errorf("failed to create category: %v", err)
	}

	return category, nil
}

// CreateExchange is the resolver for the createExchange field.
func (r *mutationResolver) CreateExchange(ctx context.Context, input generated.NewExchangeInput) (*models.Exchange, error) {
	return nil, fmt.Errorf("not implemented: CreateExchange")
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input generated.NewAccountInput) (*models.Account, error) {
	userID, err := strconv.ParseUint(input.UserID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %v", err)
	}
	
	currencyID, err := strconv.ParseUint(input.CurrencyID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid currency ID: %v", err)
	}

	balance := 0.0
	if input.Balance != nil {
		balance = *input.Balance
	}

	account := &models.Account{
		UserID:     uint(userID),
		Name:       input.Name,
		Type:       input.Type,
		CurrencyID: uint(currencyID),
		Balance:    balance,
		IsActive:   true,
	}

	if err := r.DB.Create(account).Error; err != nil {
		return nil, fmt.Errorf("failed to create account: %v", err)
	}

	return account, nil
}


// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	userID, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var user models.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	return &user, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*models.User, error) {
	var users []*models.User
	if err := r.DB.Find(&users).Error; err != nil {
		return nil, err
	}
	return users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*models.User, error) {
	var user models.User
	if err := r.DB.First(&user, id).Error; err != nil {
		return nil, err
	}
	return &user, nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*models.Account, error) {
	var account models.Account
	if err := r.DB.First(&account, id).Error; err != nil {
		return nil, fmt.Errorf("account not found: %v", err)
	}
	return &account, nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*models.Account, error) {
	var accounts []*models.Account
	if err := r.DB.Find(&accounts).Error; err != nil {
		return nil, err
	}
	return accounts, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*models.Category, error) {
	var categories []*models.Category
	if err := r.DB.Find(&categories).Error; err != nil {
		return nil, err
	}
	return categories, nil
}

// ID is the resolver for the id field.
func (r *accountResolver) ID(ctx context.Context, obj *models.Account) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *accountResolver) UserID(ctx context.Context, obj *models.Account) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// CurrencyID is the resolver for the currencyId field.
func (r *accountResolver) CurrencyID(ctx context.Context, obj *models.Account) (string, error) {
	return strconv.FormatUint(uint64(obj.CurrencyID), 10), nil
}

// ID is the resolver for the id field.
func (r *transactionResolver) ID(ctx context.Context, obj *models.Transaction) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *transactionResolver) UserID(ctx context.Context, obj *models.Transaction) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// AccountID is the resolver for the accountId field.
func (r *transactionResolver) AccountID(ctx context.Context, obj *models.Transaction) (string, error) {
	return strconv.FormatUint(uint64(obj.AccountID), 10), nil
}

// CategoryID is the resolver for the categoryId field.
func (r *transactionResolver) CategoryID(ctx context.Context, obj *models.Transaction) (*string, error) {
	if obj.CategoryID == nil {
		return nil, nil
	}
	id := strconv.FormatUint(uint64(*obj.CategoryID), 10)
	return &id, nil
}

// CurrencyID is the resolver for the currencyId field.
func (r *transactionResolver) CurrencyID(ctx context.Context, obj *models.Transaction) (string, error) {
	return strconv.FormatUint(uint64(obj.CurrencyID), 10), nil
}

// ID is the resolver for the id field.
func (r *transferResolver) ID(ctx context.Context, obj *models.Transfer) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *transferResolver) UserID(ctx context.Context, obj *models.Transfer) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// FromAccountID is the resolver for the fromAccountId field.
func (r *transferResolver) FromAccountID(ctx context.Context, obj *models.Transfer) (string, error) {
	return strconv.FormatUint(uint64(obj.FromAccountID), 10), nil
}

// ToAccountID is the resolver for the toAccountId field.
func (r *transferResolver) ToAccountID(ctx context.Context, obj *models.Transfer) (string, error) {
	return strconv.FormatUint(uint64(obj.ToAccountID), 10), nil
}

// CurrencyID is the resolver for the currencyId field.
func (r *transferResolver) CurrencyID(ctx context.Context, obj *models.Transfer) (string, error) {
	return strconv.FormatUint(uint64(obj.CurrencyID), 10), nil
}

// ID is the resolver for the id field.
func (r *categoryResolver) ID(ctx context.Context, obj *models.Category) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *categoryResolver) UserID(ctx context.Context, obj *models.Category) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// ID is the resolver for the id field.
func (r *currencyResolver) ID(ctx context.Context, obj *models.Currency) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// ID is the resolver for the id field.
func (r *exchangeResolver) ID(ctx context.Context, obj *models.Exchange) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *exchangeResolver) UserID(ctx context.Context, obj *models.Exchange) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// FromAccountID is the resolver for the fromAccountId field.
func (r *exchangeResolver) FromAccountID(ctx context.Context, obj *models.Exchange) (string, error) {
	return strconv.FormatUint(uint64(obj.FromAccountID), 10), nil
}

// ToAccountID is the resolver for the toAccountId field.
func (r *exchangeResolver) ToAccountID(ctx context.Context, obj *models.Exchange) (string, error) {
	return strconv.FormatUint(uint64(obj.ToAccountID), 10), nil
}

// FromCurrencyID is the resolver for the fromCurrencyId field.
func (r *exchangeResolver) FromCurrencyID(ctx context.Context, obj *models.Exchange) (string, error) {
	return strconv.FormatUint(uint64(obj.FromCurrencyID), 10), nil
}

// ToCurrencyID is the resolver for the toCurrencyId field.
func (r *exchangeResolver) ToCurrencyID(ctx context.Context, obj *models.Exchange) (string, error) {
	return strconv.FormatUint(uint64(obj.ToCurrencyID), 10), nil
}

// ID is the resolver for the id field.
func (r *expenseResolver) ID(ctx context.Context, obj *models.Expense) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *expenseResolver) UserID(ctx context.Context, obj *models.Expense) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// AccountID is the resolver for the accountId field.
func (r *expenseResolver) AccountID(ctx context.Context, obj *models.Expense) (string, error) {
	return strconv.FormatUint(uint64(obj.AccountID), 10), nil
}

// CurrencyID is the resolver for the currencyId field.
func (r *expenseResolver) CurrencyID(ctx context.Context, obj *models.Expense) (string, error) {
	return strconv.FormatUint(uint64(obj.CurrencyID), 10), nil
}

// ID is the resolver for the id field.
func (r *incomeResolver) ID(ctx context.Context, obj *models.Income) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// UserID is the resolver for the userId field.
func (r *incomeResolver) UserID(ctx context.Context, obj *models.Income) (string, error) {
	return strconv.FormatUint(uint64(obj.UserID), 10), nil
}

// AccountID is the resolver for the accountId field.
func (r *incomeResolver) AccountID(ctx context.Context, obj *models.Income) (string, error) {
	return strconv.FormatUint(uint64(obj.AccountID), 10), nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// Accounts is the resolver for the accounts field.
func (r *userResolver) Accounts(ctx context.Context, obj *models.User) ([]*models.Account, error) {
	var accounts []*models.Account
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&accounts).Error; err != nil {
		return nil, err
	}
	return accounts, nil
}

// Categories is the resolver for the categories field.
func (r *userResolver) Categories(ctx context.Context, obj *models.User) ([]*models.Category, error) {
	var categories []*models.Category
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&categories).Error; err != nil {
		return nil, err
	}
	return categories, nil
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *models.User) ([]*models.Transaction, error) {
	var transactions []*models.Transaction
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&transactions).Error; err != nil {
		return nil, err
	}
	return transactions, nil
}

// Expenses is the resolver for the expenses field.
func (r *userResolver) Expenses(ctx context.Context, obj *models.User) ([]*models.Expense, error) {
	var expenses []*models.Expense
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&expenses).Error; err != nil {
		return nil, err
	}
	return expenses, nil
}

// Incomes is the resolver for the incomes field.
func (r *userResolver) Incomes(ctx context.Context, obj *models.User) ([]*models.Income, error) {
	var incomes []*models.Income
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&incomes).Error; err != nil {
		return nil, err
	}
	return incomes, nil
}

// Exchanges is the resolver for the exchanges field.
func (r *userResolver) Exchanges(ctx context.Context, obj *models.User) ([]*models.Exchange, error) {
	var exchanges []*models.Exchange
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&exchanges).Error; err != nil {
		return nil, err
	}
	return exchanges, nil
}

// Transfers is the resolver for the transfers field.
func (r *userResolver) Transfers(ctx context.Context, obj *models.User) ([]*models.Transfer, error) {
	var transfers []*models.Transfer
	if err := r.DB.Where("user_id = ?", obj.ID).Find(&transfers).Error; err != nil {
		return nil, err
	}
	return transfers, nil
}

// Currencies is the resolver for the currencies field.
func (r *queryResolver) Currencies(ctx context.Context) ([]*models.Currency, error) {
	var currencies []*models.Currency
	if err := r.DB.Find(&currencies).Error; err != nil {
		return nil, err
	}
	return currencies, nil
}

// Currency is the resolver for the currency field.
func (r *queryResolver) Currency(ctx context.Context, id string) (*models.Currency, error) {
	var currency models.Currency
	if err := r.DB.First(&currency, id).Error; err != nil {
		return nil, fmt.Errorf("currency not found: %v", err)
	}
	return &currency, nil
}

// UserAccounts is the resolver for the userAccounts field.
func (r *queryResolver) UserAccounts(ctx context.Context, userID string) ([]*models.Account, error) {
	var accounts []*models.Account
	if err := r.DB.Where("user_id = ?", userID).Find(&accounts).Error; err != nil {
		return nil, err
	}
	return accounts, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*models.Category, error) {
	var category models.Category
	if err := r.DB.First(&category, id).Error; err != nil {
		return nil, fmt.Errorf("category not found: %v", err)
	}
	return &category, nil
}

// UserCategories is the resolver for the userCategories field.
func (r *queryResolver) UserCategories(ctx context.Context, userID string) ([]*models.Category, error) {
	var categories []*models.Category
	if err := r.DB.Where("user_id = ?", userID).Find(&categories).Error; err != nil {
		return nil, err
	}
	return categories, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context) ([]*models.Transaction, error) {
	var transactions []*models.Transaction
	if err := r.DB.Find(&transactions).Error; err != nil {
		return nil, err
	}
	return transactions, nil
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id string) (*models.Transaction, error) {
	var transaction models.Transaction
	if err := r.DB.First(&transaction, id).Error; err != nil {
		return nil, fmt.Errorf("transaction not found: %v", err)
	}
	return &transaction, nil
}

// UserTransactions is the resolver for the userTransactions field.
func (r *queryResolver) UserTransactions(ctx context.Context, userID string) ([]*models.Transaction, error) {
	var transactions []*models.Transaction
	if err := r.DB.Where("user_id = ?", userID).Find(&transactions).Error; err != nil {
		return nil, err
	}
	return transactions, nil
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context) ([]*models.Expense, error) {
	var expenses []*models.Expense
	if err := r.DB.Find(&expenses).Error; err != nil {
		return nil, err
	}
	return expenses, nil
}

// Expense is the resolver for the expense field.
func (r *queryResolver) Expense(ctx context.Context, id string) (*models.Expense, error) {
	var expense models.Expense
	if err := r.DB.First(&expense, id).Error; err != nil {
		return nil, fmt.Errorf("expense not found: %v", err)
	}
	return &expense, nil
}

// UserExpenses is the resolver for the userExpenses field.
func (r *queryResolver) UserExpenses(ctx context.Context, userID string) ([]*models.Expense, error) {
	var expenses []*models.Expense
	if err := r.DB.Where("user_id = ?", userID).Find(&expenses).Error; err != nil {
		return nil, err
	}
	return expenses, nil
}

// Incomes is the resolver for the incomes field.
func (r *queryResolver) Incomes(ctx context.Context) ([]*models.Income, error) {
	var incomes []*models.Income
	if err := r.DB.Find(&incomes).Error; err != nil {
		return nil, err
	}
	return incomes, nil
}

// Income is the resolver for the income field.
func (r *queryResolver) Income(ctx context.Context, id string) (*models.Income, error) {
	var income models.Income
	if err := r.DB.First(&income, id).Error; err != nil {
		return nil, fmt.Errorf("income not found: %v", err)
	}
	return &income, nil
}

// UserIncomes is the resolver for the userIncomes field.
func (r *queryResolver) UserIncomes(ctx context.Context, userID string) ([]*models.Income, error) {
	var incomes []*models.Income
	if err := r.DB.Where("user_id = ?", userID).Find(&incomes).Error; err != nil {
		return nil, err
	}
	return incomes, nil
}

// Exchanges is the resolver for the exchanges field.
func (r *queryResolver) Exchanges(ctx context.Context) ([]*models.Exchange, error) {
	var exchanges []*models.Exchange
	if err := r.DB.Find(&exchanges).Error; err != nil {
		return nil, err
	}
	return exchanges, nil
}

// Exchange is the resolver for the exchange field.
func (r *queryResolver) Exchange(ctx context.Context, id string) (*models.Exchange, error) {
	var exchange models.Exchange
	if err := r.DB.First(&exchange, id).Error; err != nil {
		return nil, fmt.Errorf("exchange not found: %v", err)
	}
	return &exchange, nil
}

// UserExchanges is the resolver for the userExchanges field.
func (r *queryResolver) UserExchanges(ctx context.Context, userID string) ([]*models.Exchange, error) {
	var exchanges []*models.Exchange
	if err := r.DB.Where("user_id = ?", userID).Find(&exchanges).Error; err != nil {
		return nil, err
	}
	return exchanges, nil
}

// Transfers is the resolver for the transfers field.
func (r *queryResolver) Transfers(ctx context.Context) ([]*models.Transfer, error) {
	var transfers []*models.Transfer
	if err := r.DB.Find(&transfers).Error; err != nil {
		return nil, err
	}
	return transfers, nil
}

// Transfer is the resolver for the transfer field.
func (r *queryResolver) Transfer(ctx context.Context, id string) (*models.Transfer, error) {
	var transfer models.Transfer
	if err := r.DB.First(&transfer, id).Error; err != nil {
		return nil, fmt.Errorf("transfer not found: %v", err)
	}
	return &transfer, nil
}

// UserTransfers is the resolver for the userTransfers field.
func (r *queryResolver) UserTransfers(ctx context.Context, userID string) ([]*models.Transfer, error) {
	var transfers []*models.Transfer
	if err := r.DB.Where("user_id = ?", userID).Find(&transfers).Error; err != nil {
		return nil, err
	}
	return transfers, nil
}

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input generated.NewExpenseInput) (*models.Expense, error) {
	return nil, fmt.Errorf("not implemented: CreateExpense")
}

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input generated.NewIncomeInput) (*models.Income, error) {
	return nil, fmt.Errorf("not implemented: CreateIncome")
}

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input generated.NewTransferInput) (*models.Transfer, error) {
	return nil, fmt.Errorf("not implemented: CreateTransfer")
}